import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Link from "next/link";

// Load custom fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Merge both functions into a single RootLayout
export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Add your navigation bar here */}
        <header className="navbar">
          <nav>
            <Link href="/">Home</Link>
            <Link href="/search">Search</Link>
          </nav>
        </header>
        {/* Render child pages */}
        <main>{children}</main>
      </body>
    </html>
  );
}